services:
    db:
        build:
            context: .
            dockerfile: Dockerfile.postgres
        environment:
            - POSTGRES_PASSWORD=musicbrainz
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        shm_size: 8gb
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U musicbrainz -d musicbrainz" ]
            interval: 5s
            timeout: 5s
            retries: 5

    mbslave:
        build:
            context: .
            dockerfile: Dockerfile.mbslave
        environment:
            - KEEP_ALIVE=true
        volumes:
            - mbslave_config:/etc/mbslave
        depends_on:
            db:
                condition: service_healthy

volumes:
    db_data:
    mbslave_config:
